# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5dbb0ddc27750cc91bdf6890b8c9d219511a268c8c8851e177db8bcd345edc6cff04aaf214760e4002b96ca33a2a3dd4d2d768a4fec179b0c51d8d531de07d07

test:
  secret_key_base: 32a1a34a28c1e04f00e1a84a8ff133bb8b1d333fb0548eb9d97b1b005aa85243bf94b7ac670a5a5c803aebbf13ee16e890d1d04df155bb9cd7fe5b3ce8931b88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
